#!/bin/bash

# This script automatically executes when the cell network connects
# Felix from Soracom provided this script -- Mike commented it out
# datetime=`date "+%Y-%m-%d %H:%M:%S"`
# echo "[$datetime] Connected" >> /home/pi/soracom.log

# Mike modified Felix's script for the DREAM project
systemctl restart dream-batcher.service
logger "Resumed connection resumed. Restarted batcher service to publish to GCP PubSub"
